Instance_Name: "test_gpu_instance"
Instance_Type: "t2.micro"
Ami_Id: "ami-03f65b8614a860c29"
#Ami_Id: "ami-0f5ee92e2d63afc18"
Action: "CREATE"
#Action: "TERMINATE"
Pytorch: "2.0"
Python: "3.10"
CUDA: "11.7"
KEY_NAME: "prateek"
Instance_id: "i-030766099c4bf7875"
Instance_Active_Window: ""
